### ISSUE TITLE
Seperate .ts files from the wwwroot directory

### ISSUE THREAD

**Issue by rugdealer** [DanWahlin/Angular-ASPNET-Core-Seed#1]
Thanks for the project, I've noticed on some other projects that the typescript files are seperated from wwwroot directory. In theory, it's only supposed to serve static files.

Would it be possible to get a seed version where the typescript files are located in an "App" or "src" on the same level as the "wwwroot" directory?

Thanks

**Comment by DanWahlin** [comment]
Thanks for the suggestion - I appreciate it.  Since the deployment process would be responsible for determining which files end up in wwwroot as the site is published, I don't have any plans to change the folder structure at this point.
